[project]
name = "hs-code-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "openai==1.68.2",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.1.0",
    "streamlit==1.44.0",
]
